### ISSUE TITLE
[Enhancement] Add a digitalRead SPI command

### ISSUE THREAD

**Issue by anecdata** [arduino/nina-fw#19]
nina-fw currently supports pinMode, analogWrite, and DigitalWrite. It would be very useful to also be able to read from the ESP32's digital pins via SPI from an attached processor.

**Comment by xelll** [comment]
it's also useful to be able to read anlog pins value

**Comment by anecdata** [comment]
Some use cases:
- GPIO expansion;
- Adafruit ESP32 Breakout and Adafruit ESP32 Feather have battery voltage on (unexposed) pin A13 / I35;
- Ability to read specially-configured ESP32 co-processor inputs would allow the main processor to determine the form factor of the attached ESP32 co-processor (e.g., Adafruit Airlift Breakout vs. Adafruit ESP32 Feather vs. Adafruit ESP32 Breakout, etc.), and adapt to its unique capabilities.

**Comment by sandeepmistry** [comment]
Hi @anecdata,

At this time, we are not interested in implementing this feature, I'm marking the issue as won't fix.

**Comment by anecdata** [comment]
Now implemented as part of #67

**Comment by xelll** [comment]
> Now implemented as part of #67

:+1:
