### ISSUE TITLE
When version 1.2.4 will be available to flash?

### ISSUE THREAD

**Issue by thalesfsp** [arduino/nina-fw#25]
Hi!

  I downloaded the latest hourly build of the Arduino IDE, and when I tried to upgrade the WiFi FW, the combobox had 1.2.3 listed as available. Should I wait for the next Arduino version, or ignore that and follows the instruction on your README.md file?

Thank you!

**Comment by per1234** [comment]
NINA firmware 1.2.4 is bundled with this test build of the Arduino IDE:
https://github.com/arduino/Arduino/pull/8976#issuecomment-503638485

**Comment by thalesfsp** [comment]
Thanks, commented there.
