### ISSUE TITLE
does not work with Arduino nano iot 33 

### ISSUE THREAD

**Issue by Russell108** [arduino/nina-fw#39]
When will it be possible to update the firmware for nano iot so fixes can be applied
I have an issue where the nano iot 33 keeps disconnecting form a network of its own accord.
I understand this used to happen to the mar 1010 but you guys found a fix & applied it in an updater

**Comment by sandeepmistry** [comment]
The firmware update tool with be updated with the following pull request in the IDE: https://github.com/arduino/Arduino/pull/9552

**Comment by sandeepmistry** [comment]
Version 1.5.0 of the WiFiNINA library will provide support to updating the NINA board using the updater: https://github.com/arduino-libraries/WiFiNINA/pull/101
