### ISSUE TITLE
Please add WIFI_ALL_CHANNEL_SCAN for multiple AP environment

### ISSUE THREAD

**Issue by wasteofpaint** [arduino/nina-fw#94]
Using Nano33iot boards with NINA FW 1.5.0 in an environment with multiple APs broadcasting the same SSID. The Arduinos do not connect to the AP with the strongest signal. If seems that this is due to the wifi module being configured to use WIFI_FAST_SCAN instead of WIFI_ALL_CHANNEL_SCAN. The default was changed to WIFI_FAST_SCAN in NINA FW version 1.2.2. Can you revert this change, or make the option user selectable for those of us that are trying to use these boards in a multi AP environment? Seems to me that the default should be ALL_CHANNEL_SCAN.

Thanks!

**Comment by per1234** [comment]
Hi @wasteofpaint. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/nina-fw/issues/75.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I will request you to close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
